### PR TITLE
Implemented the faster `/geo` call

### PR DESCRIPTION
**Pull request by Rvanlaak**
... as can be found on http://ipinfo.io/developers

### CODE REVIEW

**Comment by cmwelsh** [comment]
This is already implemented. Here is the code I use:

        $ipInfo = new Ipinfo();
        $ip = '127.0.0.1';
        $host = $ipInfo->getSpecificField($ip, Ipinfo::GEO);
        $city = $host->getCity();
        $state = $host->getRegion();
        $country = $host->getCountry();

**Comment by Rvanlaak** [comment]
You are totally right, but it isn't that clear in my opinion. Will be better to make a sort of stub call for this in my opinion.

**Comment by DavidePastore** [comment]
Hi @Rvanlaak, thanks for the interest in this project. :smile: 
Did you try to test it with `phpunit`? It seems they added the `postal` field that is not yet documented. Can you confirm this? Thanks. :cake:

**Comment by DavidePastore** [comment]
@Rvanlaak can you please rebase your PR in one commit?

**Comment by Rvanlaak** [comment]
Rebased the commits, left the documentation commit a separate one. Will test the postal for you later today

**Comment by DavidePastore** [comment]
Thanks @Rvanlaak ! You rock :guitar:

**Pull request merged**
